spring:
  application:
    name: server2

server:
  port: 8081

management:
  tracing:
    sampling:
      probability: 1.0 # 100% ???
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.springframework.http.client: DEBUG

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG